### ISSUE TITLE
Can we get some pictures of the extension in action?

### ISSUE THREAD

**Issue by telamonian** [KeshShan/markdown-live#4]
Is the vscode extension in this project functional? If so, can you please add some images, or better yet, animated gifs to the README of the extension in action?

I am [very interested](https://github.com/microsoft/vscode/issues/22068#issuecomment-620393664) in a better markdown+preview UX experience in vscode.

**Comment by KeshShan** [comment]
Hi @telamonian I have added a gif of the extension in action to the README. 
I have updated some issues and had a new release, do check it out!! 
Thank you for the issue raised

**Comment by KeshShan** [comment]
I am closing the issue for now, feel free to reopen it, if there are any concerns

**Comment by telamonian** [comment]
Thanks @KeshShan!
